package com.xkool.common.enums;

import java.util.Arrays;
import java.util.List;

import static com.xkool.common.constant.PlanningLandUsageIdConstant.*;
import static com.xkool.common.constant.PlanningLandUsageNameConstant.*;

public enum PlanningLandUsageEnum {

    RESIDENTIAL_PLANNING_LAND_USAGE(RESIDENTIAL_PLANNING_LAND_USAGE_ID, RESIDENTIAL_PLANNING_LAND_USAGE_NAME),
    TYPE_ONE_RESIDENTIAL_PLANNING_LAND_USAGE(TYPE_ONE_RESIDENTIAL_PLANNING_LAND_USAGE_ID, TYPE_ONE_RESIDENTIAL_PLANNING_LAND_USAGE_NAME),
    TYPE_ONE_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE(TYPE_ONE_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE_ID, TYPE_ONE_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE_NAME),
    TYPE_ONE_SERVICE_FACILITY_PLANNING_LAND_USAGE(TYPE_ONE_SERVICE_FACILITY_PLANNING_LAND_USAGE_ID, TYPE_ONE_SERVICE_FACILITY_PLANNING_LAND_USAGE_NAME),
    TYPE_TWO_RESIDENTIAL_PLANNING_LAND_USAGE(TYPE_TWO_RESIDENTIAL_PLANNING_LAND_USAGE_ID, TYPE_TWO_RESIDENTIAL_PLANNING_LAND_USAGE_NAME),
    TYPE_TWO_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE(TYPE_TWO_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE_ID, TYPE_TWO_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE_NAME),
    TYPE_TWO_SERVICE_FACILITY_PLANNING_LAND_USAGE(TYPE_TWO_SERVICE_FACILITY_PLANNING_LAND_USAGE_ID, TYPE_TWO_SERVICE_FACILITY_PLANNING_LAND_USAGE_NAME),
    TYPE_THREE_RESIDENTIAL_PLANNING_LAND_USAGE(TYPE_THREE_RESIDENTIAL_PLANNING_LAND_USAGE_ID, TYPE_THREE_RESIDENTIAL_PLANNING_LAND_USAGE_NAME),
    TYPE_THREE_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE(TYPE_THREE_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE_ID, TYPE_THREE_RESIDENTIAL_AND_FACILITY_PLANNING_LAND_USAGE_NAME),
    TYPE_THREE_SERVICE_FACILITY_PLANNING_LAND_USAGE(TYPE_THREE_SERVICE_FACILITY_PLANNING_LAND_USAGE_ID, TYPE_THREE_SERVICE_FACILITY_PLANNING_LAND_USAGE_NAME),
    BUSINESS_AND_FACILITY_PLANNING_LAND_USAGE(BUSINESS_AND_FACILITY_PLANNING_LAND_USAGE_ID, BUSINESS_AND_FACILITY_PLANNING_LAND_USAGE_NAME),
    BUSINESS_PLANNING_LAND_USAGE(BUSINESS_PLANNING_LAND_USAGE_ID, BUSINESS_PLANNING_LAND_USAGE_NAME),
    RETAIL_BUSINESS_PLANNING_LAND_USAGE(RETAIL_BUSINESS_PLANNING_LAND_USAGE_ID, RETAIL_BUSINESS_PLANNING_LAND_USAGE_NAME),
    WHOLESALE_MARKET_PLANNING_LAND_USAGE(WHOLESALE_MARKET_PLANNING_LAND_USAGE_ID, WHOLESALE_MARKET_PLANNING_LAND_USAGE_NAME),
    CATERING_PLANNING_LAND_USAGE(CATERING_PLANNING_LAND_USAGE_ID, CATERING_PLANNING_LAND_USAGE_NAME),
    HOSTEL_PLANNING_LAND_USAGE(HOSTEL_PLANNING_LAND_USAGE_ID, HOSTEL_PLANNING_LAND_USAGE_NAME),
    BUSINESS_FACILITIES_PLANNING_LAND_USAGE(BUSINESS_FACILITIES_PLANNING_LAND_USAGE_ID, BUSINESS_FACILITIES_PLANNING_LAND_USAGE_NAME),
    FINANCIAL_INSURANCE_PLANNING_LAND_USAGE(FINANCIAL_INSURANCE_PLANNING_LAND_USAGE_ID, FINANCIAL_INSURANCE_PLANNING_LAND_USAGE_NAME),
    ART_MEDIA_PLANNING_LAND_USAGE(ART_MEDIA_PLANNING_LAND_USAGE_ID, ART_MEDIA_PLANNING_LAND_USAGE_NAME),
    OTHER_BUSINESS_FACILITY_PLANNING_LAND_USAGE(OTHER_BUSINESS_FACILITY_PLANNING_LAND_USAGE_ID, OTHER_BUSINESS_FACILITY_PLANNING_LAND_USAGE_NAME),
    ENTERTAINMENT_AND_WELLNESS_FACILITY_PLANNING_LAND_USAGE(ENTERTAINMENT_AND_WELLNESS_FACILITY_PLANNING_LAND_USAGE_ID, ENTERTAINMENT_AND_WELLNESS_FACILITY_PLANNING_LAND_USAGE_NAME),
    ENTERTAINMENT_PLANNING_LAND_USAGE(ENTERTAINMENT_PLANNING_LAND_USAGE_ID, ENTERTAINMENT_PLANNING_LAND_USAGE_NAME),
    WELLNESS_PLANNING_LAND_USAGE(WELLNESS_PLANNING_LAND_USAGE_ID, WELLNESS_PLANNING_LAND_USAGE_NAME),
    INDUSTRY_PLANNING_LAND_USAGE(INDUSTRY_PLANNING_LAND_USAGE_ID, INDUSTRY_PLANNING_LAND_USAGE_NAME),
    TYPE_ONE_INDUSTRY_PLANNING_LAND_USAGE(TYPE_ONE_INDUSTRY_PLANNING_LAND_USAGE_ID, TYPE_ONE_INDUSTRY_PLANNING_LAND_USAGE_NAME),
    TYPE_TWO_INDUSTRY_PLANNING_LAND_USAGE(TYPE_TWO_INDUSTRY_PLANNING_LAND_USAGE_ID, TYPE_TWO_INDUSTRY_PLANNING_LAND_USAGE_NAME),
    TYPE_THREE_INDUSTRY_LAND_USAGE(TYPE_THREE_INDUSTRY_LAND_USAGE_ID, TYPE_THREE_INDUSTRY_LAND_USAGE_NAME),
    LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE(LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_ID, LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_NAME),
    TYPE_ONE_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE(TYPE_ONE_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_ID, TYPE_ONE_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_NAME),
    TYPE_TWO_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE(TYPE_TWO_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_ID, TYPE_TWO_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_NAME),
    TYPE_THREE_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE(TYPE_THREE_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_ID, TYPE_THREE_LOGISTICS_AND_WAREHOUSING_PLANNING_LAND_USAGE_NAME);

    private int id;
    private String name;

    PlanningLandUsageEnum(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }

    public static PlanningLandUsageEnum getPlanningLandUsageEnumById(int id) {
        for (PlanningLandUsageEnum planningLandUsageEnum : PlanningLandUsageEnum.values()) {
            if (planningLandUsageEnum.getId() == id) {
                return planningLandUsageEnum;
            }
        }
        return null;
    }

    public static PlanningLandUsageEnum getPlanningLandUsageEnumByName(String name) {
        for (PlanningLandUsageEnum planningLandUsageEnum : PlanningLandUsageEnum.values()) {
            if (planningLandUsageEnum.getName().equals(name)) {
                return planningLandUsageEnum;
            }
        }
        return null;
    }

    public static List<PlanningLandUsageEnum> getPlanningLandUsageEnums() {
        return Arrays.asList(PlanningLandUsageEnum.values());
    }
}
